name: nasamira
description: View the surface of the Mars with images made by NASA's rovers.

publish_to: 'none'
version: 1.1.3+8

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  splashscreen: 1.2.0
  cupertino_icons: ^0.1.2
  characters: ^1.0.0
  numberpicker: ^1.2.0
  url_launcher: ^5.4.2
  dio: ^3.0.10


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/images/
    - lib/