name: nasamira
description: View the surface of the Mars with images made by NASA's rovers.

publish_to: 'none'
version: 3.0.0+13

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  splashscreen:
    git:
      url: https://github.com/DPLYR-dev/SplashScreenFlutterPackage.git
      ref: master

  cupertino_icons: ^1.0.4
  characters: ^1.0.0
  numberpicker: ^2.1.1
  dio: ^4.0.4
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  all_lint_rules_community: ^0.0.7

flutter:
  uses-material-design: true

  assets:
    - assets/
    - lib/trans/