name: esamira
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.0.0+13

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  characters: ^1.0.0
  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  numberpicker: ^2.1.1
  spacejam: ^1.1.7
  splashscreen:
    git:
      url: https://github.com/DPLYR-dev/SplashScreenFlutterPackage.git
      ref: master


dev_dependencies:
  all_lint_rules_community: ^0.0.7
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - lib/trans/